site_name: "Le Site NSI au Lycée Jean CALVIN"
site_url: https://glaporte60.github.io/essai
repo_url: https://github.com/glaporte60/essai

docs_dir: docs

theme:
  favicon: images/favicon.ico
  icon:
    logo: material/application-variable

  custom_dir: my_theme_customizations/

  name: material
  language: fr                    # français
  palette:                        # Palettes de couleurs jour/nuit
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: teal
        accent: green
        toggle:
            icon: material/weather-sunny
            name: Passer au mode nuit
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: blue
        accent: blue
        toggle:
            icon: material/weather-night
            name: Passer au mode jour
  features:
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - toc.integrate
        - header.autohide
        - content.code.annotate 


markdown_extensions:
    - abbr
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.

    - pymdownx.superfences
    # Pour pouvoir ajouter la largeur de l'image par exemple {width=50%}
    - attr_list
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    # Pour afficher des bandeaux exemple, attention,etc
    - admonition
    - pymdownx.details              #   qui peuvent s'enrouler ou se dérouler.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight:           # Coloration syntaxique du code
        auto_title: true

    - pymdownx.tabbed:
          # Pour afficher des panneaux flottants
          alternate_style: true 
    # Pour afficher des emojis
    - pymdownx.emoji
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - md_in_html
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

    
      
# Pour ajouter des pages    
nav:
    - 'Accueil' : 'index.md'
    - '1NSI':
        - 'Chapitre1': '1NSI/ch01/bases.md'
    - 'TNSI':
        - 'Révisions': 'TNSI/Revisions/Revisions.md'
        - 'Bases de Données': 'TNSI/Bases_De_Donnees/Bases_De_Donnees.md'
    - 'A propos' : 'a_propos.md'

plugins:
    - search
    - sqlite-console
    - macros


extra_javascript:
  - xtra/config.js                    # MathJax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - xtra/javascripts/interpreter.js

extra_css:
  - xtra/stylesheets/pyoditeur.css
  - xtra/ajustements.css           # ajustements